apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-example
  namespace: node-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
        - name: node-example
          image: tarunkoshti/node-example:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      #     volumeMounts:
      #       - name: node-example-storage
      #         mountPath: /app/public
      # volumes:
      #   - name: node-example-storage
      #     persistentVolumeClaim:
      #       claimName: node-example-pvc
