# minikube addons enable ingress
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: node-example
#   namespace: node-example
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: node-example.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: node-example
#                 port:
#                   number: 80
