apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-example
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: node-example=tarunkoshti/node-example
    argocd-image-updater.argoproj.io/node-example.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/tarun-koshti/node-example-argocd.git
    targetRevision: main
    path: k8s
    kustomize: {} # <- THIS enables supported source type
  destination:
    server: https://kubernetes.default.svc
    namespace: node-example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
